#version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cropdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7
    ports:
      - 6379:6379
    command: ["redis-server", "--save", "60", "1"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - backend
      - redis
      - minio
    volumes:
      - ./backend:/app
    command: celery -A app.workers.celery_app.celery worker --loglevel=info

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgdata:
  minio-data:
