"""init schema

Revision ID: dc29f44d279d
Revises: 
Create Date: 2025-09-03 18:53:29.712888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc29f44d279d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('measurements', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('measurements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_measurements_device_id'), 'measurements', ['device_id'], unique=False)
    op.create_index('ix_measurements_device_time', 'measurements', ['device_id', sa.text('time DESC')], unique=False)
    op.create_index(op.f('ix_measurements_message_id'), 'measurements', ['message_id'], unique=True)
    op.create_index(op.f('ix_measurements_time'), 'measurements', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_time'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_message_id'), table_name='measurements')
    op.drop_index('ix_measurements_device_time', table_name='measurements')
    op.drop_index(op.f('ix_measurements_device_id'), table_name='measurements')
    op.drop_column('measurements', 'created_at')
    op.drop_column('measurements', 'message_id')
    op.drop_column('measurements', 'id')
    # ### end Alembic commands ###
